name: Louise Ebrey
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2885305
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Louise Ebrey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#60003d'
    - '#cc3d3f'
    - '#dd7844'
    - '#22444e'
  brandStrength: 0.8243728
  lightness: 0.5878136
  saturation: 0.6666667
  rhythmicContrast: 0.5215054
purpose: []
